HOST: http://www.google.com/

--- SeedBoxer API v2.1 ---
---
Welcome to the SeedBoxer API documentation.

SeedBoxer is a distribution content system based on users queues and filters. It was designed to be hosted inside a Seed Box, a remote server used to download and share content through the Internet. SeedBoxer was created to work with downloads managers like rtorrent, utorrent, trasmission. This managers need to be configured to use watch, in progress and complete folders.

Check our page http://seedboxer.net or the https://github.com/seedboxer/seedboxer/wiki.
---

--
Users Resources
The following is a section of resources related to the users
--
Show the download status for the given user
GET /status?apikey={apikey}
< 200
< Accept: application/json
< Content-Type: application/json
{
    "download": {
        "size": 15016,
        "fileName": "Homeland.S01.720p.HDTV.x264",
        "transferred": 9029
    },
    "downloadStatus": "STARTED",
    "message": null,
    "status": null
}

Save new products in your shopping cart
GET /start?apikey={apikey}
< 200
< Accept: application/json
< Content-Type: application/json
{
    "message": null,
    "status": "SUCCESS"
}


-- Downloads Resources --
List all available downloads on the server (complete and in progress folder)
GET /downloads/list?apikey={apikey}
< 200
[
    {
        "name": "Go.On.S01E14.720p.HDTV.X264-DIMENSION",
        "order": 0,
        "queueId": null,
        "downloaded": false
    }
]