#!/bin/bash

set -e

# source debconf library
. /usr/share/debconf/confmodule

# Source dbconfig-common functions
if [ -f /usr/share/dbconfig-common/dpkg/prerm.mysql  ]; then
  . /usr/share/dbconfig-common/dpkg/prerm.mysql
fi
 
dbc_go seedboxer-standalone $@

#DEBHELPER#
